name: CD

on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: will413028/attendance-system-backend:latest
          
      - 
        name: Heroku
        uses: actions/checkout@v2
      - 
        name: Heroku Push
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fast-gorge-70763"
          heroku_email: "will413028@gmail.com"
